"""v0.1: identidade e permissao (usuarios: mfa/bloqueio, audit_log)

Revision ID: 3cdd1f03f29c
Revises: bba8fd2aebda
Create Date: 2026-09-10 23:11:25.644162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cdd1f03f29c'
down_revision: Union[str, Sequence[str], None] = 'bba8fd2aebda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id_log', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tabela_afetada', sa.String(), nullable=True),
    sa.Column('id_registro_afetado', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=True),
    sa.Column('dados_antes', sa.Text(), nullable=True),
    sa.Column('dados_depois', sa.Text(), nullable=True),
    sa.Column('ip_origem', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_log')
    )
    op.create_index(op.f('ix_audit_log_acao'), 'audit_log', ['acao'], unique=False)
    op.create_index(op.f('ix_audit_log_id_log'), 'audit_log', ['id_log'], unique=False)
    op.create_index(op.f('ix_audit_log_tabela_afetada'), 'audit_log', ['tabela_afetada'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.add_column('usuarios', sa.Column('tentativas_falhas', sa.Integer(), nullable=True))
    op.add_column('usuarios', sa.Column('bloqueado_ate', sa.DateTime(), nullable=True))
    op.add_column('usuarios', sa.Column('mfa_secret', sa.String(), nullable=True))
    op.add_column('usuarios', sa.Column('mfa_ativado', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'mfa_ativado')
    op.drop_column('usuarios', 'mfa_secret')
    op.drop_column('usuarios', 'bloqueado_ate')
    op.drop_column('usuarios', 'tentativas_falhas')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tabela_afetada'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id_log'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_acao'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
